spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

logging:
  level:
    org.hibernate.type: debug